### ISSUE TITLE
Allow players in other factions to access locked blocks if they are given access.

### ISSUE THREAD

**Issue by dmccoystephenson** [DansPlugins/Medieval-Factions#632] opened 2020-09-01 02:16 UTC

**Comment by philbgarner** [comment] 2020-09-01 20:21
Inspecting the code, it looks like this is already possible.  Have we confirmed this bug?

**Comment by dmccoystephenson** [comment] 2020-09-01 21:41
Currently if you're not in a faction and you try to interact with something on their land, the event is cancelled.

The purpose of this issue is to add an exception where if the player is trying to interact with a locked block in the territory of a faction they don't belong to, they will be allowed as long as they are given access to the locked block.

I don't think that exception has been programmed, and I believe the current behavior is that if someone is not in your faction, then they can't access any locked blocks in your territory even if they are granted access.

**Comment by philbgarner** [comment] 2020-09-02 23:47
Thanks, I wasn't sure where else to look.  I'll check there.

**Comment by philbgarner** [comment] 2020-09-02 23:57
Not tested, but I think it will probably be resolved by moving the check claim code in playerinteractevent to happen after the locked block code is checked, that way the locked block logic happens before the player is rejected because it's inside another faction's territory.

**Closed** 2020-09-02 23:57 UTC
Labels: easy, improvement, next release
